# Defines and orchestrates all services (PostgreSQL, Redis, appointment-service, frontend-service) for local or cloud deployment.

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medisync
    ports:
      - "5432:5432"