# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: appointment.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'appointment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ppointment.proto\x12\x0b\x61ppointment\"A\n\x12\x41ppointmentRequest\x12\x11\n\tdoctor_id\x18\x01 \x01(\x05\x12\x18\n\x10\x61ppointment_date\x18\x02 \x01(\t\"\x7f\n\x0f\x41ppointmentSlot\x12\x0f\n\x07slot_id\x18\x01 \x01(\x05\x12\x11\n\tdoctor_id\x18\x02 \x01(\x05\x12\x18\n\x10\x61ppointment_date\x18\x03 \x01(\t\x12\x18\n\x10\x61ppointment_time\x18\x04 \x01(\t\x12\x14\n\x0cis_available\x18\x05 \x01(\x08\">\n\x0f\x41ppointmentList\x12+\n\x05slots\x18\x01 \x03(\x0b\x32\x1c.appointment.AppointmentSlot\":\n\x16\x42ookAppointmentRequest\x12\x0f\n\x07slot_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"+\n\x18\x43\x61ncelAppointmentRequest\x12\x0f\n\x07slot_id\x18\x01 \x01(\x05\"0\n\x0c\x43onfirmation\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb9\x02\n\x19\x41ppointmentFrontendBridge\x12[\n\x1a\x46\x65tchAvailableAppointments\x12\x1f.appointment.AppointmentRequest\x1a\x1c.appointment.AppointmentList\x12[\n\x19RequestAppointmentBooking\x12#.appointment.BookAppointmentRequest\x1a\x19.appointment.Confirmation\x12\x62\n\x1eRequestAppointmentCancellation\x12%.appointment.CancelAppointmentRequest\x1a\x19.appointment.Confirmation2\x92\x02\n\x12\x41ppointmentService\x12R\n\x11LookupAppointment\x12\x1f.appointment.AppointmentRequest\x1a\x1c.appointment.AppointmentList\x12Q\n\x0f\x42ookAppointment\x12#.appointment.BookAppointmentRequest\x1a\x19.appointment.Confirmation\x12U\n\x11\x43\x61ncelAppointment\x12%.appointment.CancelAppointmentRequest\x1a\x19.appointment.Confirmationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'appointment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPOINTMENTREQUEST']._serialized_start=34
  _globals['_APPOINTMENTREQUEST']._serialized_end=99
  _globals['_APPOINTMENTSLOT']._serialized_start=101
  _globals['_APPOINTMENTSLOT']._serialized_end=228
  _globals['_APPOINTMENTLIST']._serialized_start=230
  _globals['_APPOINTMENTLIST']._serialized_end=292
  _globals['_BOOKAPPOINTMENTREQUEST']._serialized_start=294
  _globals['_BOOKAPPOINTMENTREQUEST']._serialized_end=352
  _globals['_CANCELAPPOINTMENTREQUEST']._serialized_start=354
  _globals['_CANCELAPPOINTMENTREQUEST']._serialized_end=397
  _globals['_CONFIRMATION']._serialized_start=399
  _globals['_CONFIRMATION']._serialized_end=447
  _globals['_APPOINTMENTFRONTENDBRIDGE']._serialized_start=450
  _globals['_APPOINTMENTFRONTENDBRIDGE']._serialized_end=763
  _globals['_APPOINTMENTSERVICE']._serialized_start=766
  _globals['_APPOINTMENTSERVICE']._serialized_end=1040
# @@protoc_insertion_point(module_scope)
